### ISSUE TITLE
Question about _Info.plist

### ISSUE THREAD

**Issue by voidref** [balthisar/middlemac#1]
Does the Contents/_Info.plist serve a function?

**Comment by voidref** [comment]
Found the doc, nm!

**Comment by balthisar** [comment]
@voidref, no problem. I hope it works out for you. Let me know if there are any issues.

**Comment by voidref** [comment]
It's working very well, except for some ruby tool hiccups, it's great.

If I may:

    gem install bundler

needs a `sudo` prepended

    ./middlemac.rb --server free

needs to be done in a separate terminal, or appended with & to run in the background so you can run the following line.

The `gem` stuff, at least on my system, needed to be updated a few times before the right versions of the dependencies got pulled in: `gem update` and `bundle update` I think it was.

Not at all being familiar with the Ruby side of things, this threw me for a loop for a bit.

Thanks again!
